apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
      - name: {{ .Release.Name }}-mysql
        image: {{ .Values.mysql.image }}
        ports:
        - name: mysql
          containerPort: 3306
        env:
        {{- range .Values.mysql.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}