apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
      - name: {{ .Release.Name }}-app
        image: {{ .Values.app.image }}
        ports:
        - name: http
          containerPort: 8080
        env:
        {{- range .Values.app.env }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}