app:
  image: rajnautiyal/movies-app
  tag: latest
  replicas: 1
  service:
    type: ClusterIP
    port: 8080
  env:
    - name: SPRING_DATASOURCE_URL
      value: jdbc:mysql://mymovie-mysql:3306/movie_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    - name: SPRING_DATASOURCE_USERNAME
      value: myuser
    - name: SPRING_DATASOURCE_PASSWORD
      value: mypassword
mysql:
  image: mysql:5.7
  replicas: 1
  service:
    type: ClusterIP
    port: 3306
  env:
    - name: MYSQL_ROOT_PASSWORD
      value: myrootpassword
    - name: MYSQL_DATABASE
      value: mydb
    - name: MYSQL_USER
      value: myuser
    - name: MYSQL_PASSWORD
      value: mypassword